server:
  servlet:
    #  定义项目的访问访问路径
    context-path: /onlineshopping-consumer-server
    # 定义端口号
  port: 7021
spring:
  application:
    # 定义应用名称，即服务名称
    name: onlineshopping-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5080/onlineshopping-eureka-server/eureka